name: deploy-mkdocs
on:
  push:
    branches:
      - main # اگر شاخه اصلی مخزن شما master است، کلمه main را به master تغییر دهید
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # این خط کلیدی است که باید اضافه شود
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force